/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hope.superresolution.autofocus;

import java.awt.event.FocusAdapter;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Microscope
 */
public class FocusRecordReviewFrame extends javax.swing.JFrame {

    private Map<String, FiducialAutoFocus.ZTravelRecord> sharedTravelRecord_ = null;
    private SortedSet<String> keySet_;
    private DefaultComboBoxModel comboBox_ = null;
    
    
    /**
     * Creates new form FocusRecordReview
     */
    public FocusRecordReviewFrame( Map<String, FiducialAutoFocus.ZTravelRecord> synchronizedRecord ) {
        sharedTravelRecord_ = synchronizedRecord;
        initComponents();
        jComboBox1.addFocusListener(new FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        } );
        if( sharedTravelRecord_ != null ) {
            comboBox_ = new DefaultComboBoxModel(sharedTravelRecord_.keySet().toArray());
            jComboBox1.setModel(comboBox_);
            if( !sharedTravelRecord_.keySet().isEmpty() ) {
                jComboBox1.setSelectedIndex(0);
            }
        }
        
        /** First Number Ordering Comparator **/
        Comparator orderComp = new Comparator() {
            
            /**
             * Takes Strings
             * 
             * @param o1
             * @param o2
             * @return 
             */
            @Override
            public int compare(Object o1, Object o2) {
                String s1 = (String) o1;
                String s2 = (String) o2;
                
                int val1 = Integer.parseInt(s1.substring(0, s1.indexOf( " ")));
                int val2 = Integer.parseInt(s2.substring(0, s2.indexOf(" ") ));
                
                return val1 - val2;
                
            }
            
        };
        
        keySet_ = new TreeSet(orderComp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Focus Review For Autofocus Number:");

        jTable1.setModel(new FiducialAutoFocus.ZTravelRecord(0)
        );
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
            
        if( sharedTravelRecord_!= null && sharedTravelRecord_.keySet() != null ) {
            //Get Last Item
            String key = (String) jComboBox1.getSelectedItem(); 
            
            //Inefficient but this is for verification purposes so low priority

            keySet_.addAll(sharedTravelRecord_.keySet());
            comboBox_ = new DefaultComboBoxModel(keySet_.toArray());
            jComboBox1.setModel(comboBox_);
            
            if( key != null ) {
                comboBox_.setSelectedItem( key );
            }
            
        } else {
            jComboBox1.setModel(new DefaultComboBoxModel(new Object[]{""} ) );
            comboBox_ = null;
        }
    }//GEN-LAST:event_formFocusGained

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        JComboBox<Integer> cb = (JComboBox)evt.getSource();
        String idx;
        try{
            idx = (String)cb.getSelectedItem();
        } catch ( ClassCastException ex ) {
            //The Model was set back to a default
            //Just return
            return;
        }
        try {
            FiducialAutoFocus.ZTravelRecord rec = sharedTravelRecord_.get(idx);
            if( rec != null ) {
                jTable1.setModel(rec);
            } else {
                //Delete any extra rows
                DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
                int rowCount = dm.getRowCount();
                //Remove rows one by one from the end of the table
                for (int a = rowCount - 1; a >= 0; a--) {
                    dm.removeRow(a);
                }
            }
        } catch (NumberFormatException ex) {
            //It's just a null value
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if( isVisible() ) {
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FocusRecordReviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FocusRecordReviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FocusRecordReviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FocusRecordReviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        final Map<String, FiducialAutoFocus.ZTravelRecord> map = new HashMap<String, FiducialAutoFocus.ZTravelRecord>();
        FiducialAutoFocus.ZTravelRecord req = new FiducialAutoFocus.ZTravelRecord(144);
        req.addStepRecord( new FiducialAutoFocus.ZStepRecord(12, 133, .09, 12, 100, true, 1231));
        map.put(12 + "Extra", req);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FocusRecordReviewFrame(map).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
